<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Manage</name>
   <tag></tag>
   <elementGuidId>4aac22b9-fe0d-434d-812a-c99ea9e96455</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;full-height ng-scope layout-row&quot;]/div[@class=&quot;layout-fill ng-scope layout-row&quot;]/div[@class=&quot;admin-panel layout-column flex&quot;]/md-content[@class=&quot;layout-fill _md flex&quot;]/div[@class=&quot;ng-scope&quot;]/div[@id=&quot;admin-panel-content-view&quot;]/div[@id=&quot;admin-panel-content-view&quot;]/md-table-container[@class=&quot;ng-scope&quot;]/table[@class=&quot;ng-pristine ng-untouched ng-valid md-table ng-isolate-scope&quot;]/tbody[@class=&quot;md-body&quot;]/tr[@class=&quot;md-row ng-scope ng-isolate-scope&quot;]/td[6]/span[1]/md-menu[@class=&quot;md-menu ng-scope _md&quot;]/button[@class=&quot;md-icon-button md-button md-ink-ripple&quot;]/span[@class=&quot;ng-scope&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='admin-panel-content-view']/md-table-container/table/tbody/tr/td[6]/span/md-menu/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='female'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THOBILE'])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select An Option Below'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Customer'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//span/md-menu/button/span</value>
   </webElementXpaths>
</WebElementEntity>
